# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
seed_params = [ {:title => 'OSecondArticle', :author => 	Author.create(:name => 'Barista'), :body =>	'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.' 
},
{ 	:title => 'OHow to Hipster', :author => Author.create(:name => 'Bar E. Sta'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.' 

},
{ :title => 'OAnother One', :author => 	Author.create(:name => 'Some Guy'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
}, 
{:title => 'OBattle of Bacon', :author => Author.create(:name => 'Big Bad Wolf'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
},
{ :title => 'OHow to Ipsum', :author => Author.create(:name => 'Some Guy'), :body =>	'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.' 
},
{:title => 'OCurabitur gravida', :author => Author.create(:name => 'Elementum'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
}, 
{ :title => 'ODangers of Mice', :author => Author.create(:name => 'Cheese Wheel'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
}, 
{ :title => 'ODangers of Cheese', :author => Author.create(:name => 'Hungry Mouse'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
},
{ :title => 'OSwimming with Dolphins', :author => Author.create(:name => 'Aquaman'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
}, 
{ :title => 'OWhy Im Better than Aquaman', :author => Author.create(:name => 'Anyone Else'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
},
{ :title => 'OFirst World Problems', :author => Author.create(:name => 'Tiffany'), :body => 'Duis sollicitudin sem ac sem suscipit vel egestas lacus porttitor. Integer bibendum venenatis venenatis. Morbi scelerisque bibendum mauris vel euismod. Phasellus nunc mi, mattis ac consectetur non, semper et lectus. Donec pharetra, mauris in iaculis placerat, erat felis varius mi, in facilisis mi dui a sapien. Aliquam interdum sem ut tellus blandit suscipit. Vivamus erat leo, pellentesque eu lacinia tempor, convallis nec massa. Etiam at mauris sit amet dolor volutpat rhoncus nec quis urna. Fusce a libero eget eros sodales sodales. Morbi a scelerisque purus. Donec congue fringilla leo nec ornare. Suspendisse scelerisque quam eget sapien feugiat posuere.

Vestibulum ac mi in est tempus gravida. Integer sed urna eget mauris mollis posuere ac adipiscing diam. Donec vel justo sed magna suscipit mattis. In vestibulum turpis ut quam vehicula egestas. Duis sagittis eros diam, vel congue eros. Quisque eu justo vel quam laoreet ullamcorper. Ut turpis lacus, accumsan in commodo vitae, gravida vel sem. Curabitur massa nunc, ornare aliquet vestibulum eget, egestas a quam. Mauris scelerisque lectus eget ligula mattis feugiat tincidunt metus bibendum. Vivamus pretium nunc in odio fringilla placerat. Nulla mollis dolor sed lorem gravida ut porttitor dolor vulputate. Morbi malesuada magna id purus lacinia id semper mauris dapibus. Quisque at justo sit amet velit pulvinar dictum vel non nulla. Mauris dui mauris, faucibus nec vulputate at, vehicula sit amet sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
}
]

seed_params.each do |attributes|
   Article.create!(attributes)
end